// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: grpcIContoursExtractorService.proto
#ifndef GRPC_grpcIContoursExtractorService_2eproto__INCLUDED
#define GRPC_grpcIContoursExtractorService_2eproto__INCLUDED

#include "grpcIContoursExtractorService.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpcIContoursExtractor {

class grpcIContoursExtractorService final {
 public:
  static constexpr char const* service_full_name() {
    return "grpcIContoursExtractor.grpcIContoursExtractorService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status extract(::grpc::ClientContext* context, const ::grpcIContoursExtractor::extractRequest& request, ::grpcIContoursExtractor::extractResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpcIContoursExtractor::extractResponse>> Asyncextract(::grpc::ClientContext* context, const ::grpcIContoursExtractor::extractRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpcIContoursExtractor::extractResponse>>(AsyncextractRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpcIContoursExtractor::extractResponse>> PrepareAsyncextract(::grpc::ClientContext* context, const ::grpcIContoursExtractor::extractRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpcIContoursExtractor::extractResponse>>(PrepareAsyncextractRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void extract(::grpc::ClientContext* context, const ::grpcIContoursExtractor::extractRequest* request, ::grpcIContoursExtractor::extractResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void extract(::grpc::ClientContext* context, const ::grpcIContoursExtractor::extractRequest* request, ::grpcIContoursExtractor::extractResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::grpcIContoursExtractor::extractResponse>* AsyncextractRaw(::grpc::ClientContext* context, const ::grpcIContoursExtractor::extractRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::grpcIContoursExtractor::extractResponse>* PrepareAsyncextractRaw(::grpc::ClientContext* context, const ::grpcIContoursExtractor::extractRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status extract(::grpc::ClientContext* context, const ::grpcIContoursExtractor::extractRequest& request, ::grpcIContoursExtractor::extractResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpcIContoursExtractor::extractResponse>> Asyncextract(::grpc::ClientContext* context, const ::grpcIContoursExtractor::extractRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpcIContoursExtractor::extractResponse>>(AsyncextractRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpcIContoursExtractor::extractResponse>> PrepareAsyncextract(::grpc::ClientContext* context, const ::grpcIContoursExtractor::extractRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpcIContoursExtractor::extractResponse>>(PrepareAsyncextractRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void extract(::grpc::ClientContext* context, const ::grpcIContoursExtractor::extractRequest* request, ::grpcIContoursExtractor::extractResponse* response, std::function<void(::grpc::Status)>) override;
      void extract(::grpc::ClientContext* context, const ::grpcIContoursExtractor::extractRequest* request, ::grpcIContoursExtractor::extractResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::grpcIContoursExtractor::extractResponse>* AsyncextractRaw(::grpc::ClientContext* context, const ::grpcIContoursExtractor::extractRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::grpcIContoursExtractor::extractResponse>* PrepareAsyncextractRaw(::grpc::ClientContext* context, const ::grpcIContoursExtractor::extractRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_extract_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status extract(::grpc::ServerContext* context, const ::grpcIContoursExtractor::extractRequest* request, ::grpcIContoursExtractor::extractResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_extract : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_extract() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_extract() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status extract(::grpc::ServerContext* /*context*/, const ::grpcIContoursExtractor::extractRequest* /*request*/, ::grpcIContoursExtractor::extractResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestextract(::grpc::ServerContext* context, ::grpcIContoursExtractor::extractRequest* request, ::grpc::ServerAsyncResponseWriter< ::grpcIContoursExtractor::extractResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_extract<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_extract : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_extract() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpcIContoursExtractor::extractRequest, ::grpcIContoursExtractor::extractResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpcIContoursExtractor::extractRequest* request, ::grpcIContoursExtractor::extractResponse* response) { return this->extract(context, request, response); }));}
    void SetMessageAllocatorFor_extract(
        ::grpc::MessageAllocator< ::grpcIContoursExtractor::extractRequest, ::grpcIContoursExtractor::extractResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::grpcIContoursExtractor::extractRequest, ::grpcIContoursExtractor::extractResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_extract() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status extract(::grpc::ServerContext* /*context*/, const ::grpcIContoursExtractor::extractRequest* /*request*/, ::grpcIContoursExtractor::extractResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* extract(
      ::grpc::CallbackServerContext* /*context*/, const ::grpcIContoursExtractor::extractRequest* /*request*/, ::grpcIContoursExtractor::extractResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_extract<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_extract : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_extract() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_extract() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status extract(::grpc::ServerContext* /*context*/, const ::grpcIContoursExtractor::extractRequest* /*request*/, ::grpcIContoursExtractor::extractResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_extract : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_extract() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_extract() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status extract(::grpc::ServerContext* /*context*/, const ::grpcIContoursExtractor::extractRequest* /*request*/, ::grpcIContoursExtractor::extractResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestextract(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_extract : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_extract() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->extract(context, request, response); }));
    }
    ~WithRawCallbackMethod_extract() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status extract(::grpc::ServerContext* /*context*/, const ::grpcIContoursExtractor::extractRequest* /*request*/, ::grpcIContoursExtractor::extractResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* extract(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_extract : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_extract() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::grpcIContoursExtractor::extractRequest, ::grpcIContoursExtractor::extractResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::grpcIContoursExtractor::extractRequest, ::grpcIContoursExtractor::extractResponse>* streamer) {
                       return this->Streamedextract(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_extract() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status extract(::grpc::ServerContext* /*context*/, const ::grpcIContoursExtractor::extractRequest* /*request*/, ::grpcIContoursExtractor::extractResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedextract(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::grpcIContoursExtractor::extractRequest,::grpcIContoursExtractor::extractResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_extract<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_extract<Service > StreamedService;
};

}  // namespace grpcIContoursExtractor


#endif  // GRPC_grpcIContoursExtractorService_2eproto__INCLUDED
