// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcIStereoCameraCalibrationService.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_grpcIStereoCameraCalibrationService_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_grpcIStereoCameraCalibrationService_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021009 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/empty.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_grpcIStereoCameraCalibrationService_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_grpcIStereoCameraCalibrationService_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_grpcIStereoCameraCalibrationService_2eproto;
namespace grpcIStereoCameraCalibration {
class calibrateRequest;
struct calibrateRequestDefaultTypeInternal;
extern calibrateRequestDefaultTypeInternal _calibrateRequest_default_instance_;
class calibrateResponse;
struct calibrateResponseDefaultTypeInternal;
extern calibrateResponseDefaultTypeInternal _calibrateResponse_default_instance_;
}  // namespace grpcIStereoCameraCalibration
PROTOBUF_NAMESPACE_OPEN
template<> ::grpcIStereoCameraCalibration::calibrateRequest* Arena::CreateMaybeMessage<::grpcIStereoCameraCalibration::calibrateRequest>(Arena*);
template<> ::grpcIStereoCameraCalibration::calibrateResponse* Arena::CreateMaybeMessage<::grpcIStereoCameraCalibration::calibrateResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace grpcIStereoCameraCalibration {

// ===================================================================

class calibrateRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:grpcIStereoCameraCalibration.calibrateRequest) */ {
 public:
  inline calibrateRequest() : calibrateRequest(nullptr) {}
  ~calibrateRequest() override;
  explicit PROTOBUF_CONSTEXPR calibrateRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  calibrateRequest(const calibrateRequest& from);
  calibrateRequest(calibrateRequest&& from) noexcept
    : calibrateRequest() {
    *this = ::std::move(from);
  }

  inline calibrateRequest& operator=(const calibrateRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline calibrateRequest& operator=(calibrateRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const calibrateRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const calibrateRequest* internal_default_instance() {
    return reinterpret_cast<const calibrateRequest*>(
               &_calibrateRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(calibrateRequest& a, calibrateRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(calibrateRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(calibrateRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  calibrateRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<calibrateRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const calibrateRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const calibrateRequest& from) {
    calibrateRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(calibrateRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "grpcIStereoCameraCalibration.calibrateRequest";
  }
  protected:
  explicit calibrateRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kImages1FieldNumber = 2,
    kImages2FieldNumber = 3,
    kCamParams1FieldNumber = 4,
    kCamParams2FieldNumber = 5,
    kTransformationFieldNumber = 6,
    kRectParams1FieldNumber = 7,
    kRectParams2FieldNumber = 8,
    kGrpcServerCompressionFormatFieldNumber = 1,
  };
  // bytes images1 = 2;
  void clear_images1();
  const std::string& images1() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_images1(ArgT0&& arg0, ArgT... args);
  std::string* mutable_images1();
  PROTOBUF_NODISCARD std::string* release_images1();
  void set_allocated_images1(std::string* images1);
  private:
  const std::string& _internal_images1() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_images1(const std::string& value);
  std::string* _internal_mutable_images1();
  public:

  // bytes images2 = 3;
  void clear_images2();
  const std::string& images2() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_images2(ArgT0&& arg0, ArgT... args);
  std::string* mutable_images2();
  PROTOBUF_NODISCARD std::string* release_images2();
  void set_allocated_images2(std::string* images2);
  private:
  const std::string& _internal_images2() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_images2(const std::string& value);
  std::string* _internal_mutable_images2();
  public:

  // bytes camParams1 = 4;
  void clear_camparams1();
  const std::string& camparams1() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_camparams1(ArgT0&& arg0, ArgT... args);
  std::string* mutable_camparams1();
  PROTOBUF_NODISCARD std::string* release_camparams1();
  void set_allocated_camparams1(std::string* camparams1);
  private:
  const std::string& _internal_camparams1() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_camparams1(const std::string& value);
  std::string* _internal_mutable_camparams1();
  public:

  // bytes camParams2 = 5;
  void clear_camparams2();
  const std::string& camparams2() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_camparams2(ArgT0&& arg0, ArgT... args);
  std::string* mutable_camparams2();
  PROTOBUF_NODISCARD std::string* release_camparams2();
  void set_allocated_camparams2(std::string* camparams2);
  private:
  const std::string& _internal_camparams2() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_camparams2(const std::string& value);
  std::string* _internal_mutable_camparams2();
  public:

  // bytes transformation = 6;
  void clear_transformation();
  const std::string& transformation() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_transformation(ArgT0&& arg0, ArgT... args);
  std::string* mutable_transformation();
  PROTOBUF_NODISCARD std::string* release_transformation();
  void set_allocated_transformation(std::string* transformation);
  private:
  const std::string& _internal_transformation() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_transformation(const std::string& value);
  std::string* _internal_mutable_transformation();
  public:

  // bytes rectParams1 = 7;
  void clear_rectparams1();
  const std::string& rectparams1() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_rectparams1(ArgT0&& arg0, ArgT... args);
  std::string* mutable_rectparams1();
  PROTOBUF_NODISCARD std::string* release_rectparams1();
  void set_allocated_rectparams1(std::string* rectparams1);
  private:
  const std::string& _internal_rectparams1() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_rectparams1(const std::string& value);
  std::string* _internal_mutable_rectparams1();
  public:

  // bytes rectParams2 = 8;
  void clear_rectparams2();
  const std::string& rectparams2() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_rectparams2(ArgT0&& arg0, ArgT... args);
  std::string* mutable_rectparams2();
  PROTOBUF_NODISCARD std::string* release_rectparams2();
  void set_allocated_rectparams2(std::string* rectparams2);
  private:
  const std::string& _internal_rectparams2() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_rectparams2(const std::string& value);
  std::string* _internal_mutable_rectparams2();
  public:

  // int32 grpcServerCompressionFormat = 1;
  void clear_grpcservercompressionformat();
  int32_t grpcservercompressionformat() const;
  void set_grpcservercompressionformat(int32_t value);
  private:
  int32_t _internal_grpcservercompressionformat() const;
  void _internal_set_grpcservercompressionformat(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:grpcIStereoCameraCalibration.calibrateRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr images1_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr images2_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr camparams1_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr camparams2_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr transformation_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr rectparams1_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr rectparams2_;
    int32_t grpcservercompressionformat_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_grpcIStereoCameraCalibrationService_2eproto;
};
// -------------------------------------------------------------------

class calibrateResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:grpcIStereoCameraCalibration.calibrateResponse) */ {
 public:
  inline calibrateResponse() : calibrateResponse(nullptr) {}
  ~calibrateResponse() override;
  explicit PROTOBUF_CONSTEXPR calibrateResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  calibrateResponse(const calibrateResponse& from);
  calibrateResponse(calibrateResponse&& from) noexcept
    : calibrateResponse() {
    *this = ::std::move(from);
  }

  inline calibrateResponse& operator=(const calibrateResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline calibrateResponse& operator=(calibrateResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const calibrateResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const calibrateResponse* internal_default_instance() {
    return reinterpret_cast<const calibrateResponse*>(
               &_calibrateResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(calibrateResponse& a, calibrateResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(calibrateResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(calibrateResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  calibrateResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<calibrateResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const calibrateResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const calibrateResponse& from) {
    calibrateResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(calibrateResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "grpcIStereoCameraCalibration.calibrateResponse";
  }
  protected:
  explicit calibrateResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTransformationFieldNumber = 1,
    kRectParams1FieldNumber = 2,
    kRectParams2FieldNumber = 3,
    kXpcfGrpcReturnValueFieldNumber = 4,
  };
  // bytes transformation = 1;
  void clear_transformation();
  const std::string& transformation() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_transformation(ArgT0&& arg0, ArgT... args);
  std::string* mutable_transformation();
  PROTOBUF_NODISCARD std::string* release_transformation();
  void set_allocated_transformation(std::string* transformation);
  private:
  const std::string& _internal_transformation() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_transformation(const std::string& value);
  std::string* _internal_mutable_transformation();
  public:

  // bytes rectParams1 = 2;
  void clear_rectparams1();
  const std::string& rectparams1() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_rectparams1(ArgT0&& arg0, ArgT... args);
  std::string* mutable_rectparams1();
  PROTOBUF_NODISCARD std::string* release_rectparams1();
  void set_allocated_rectparams1(std::string* rectparams1);
  private:
  const std::string& _internal_rectparams1() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_rectparams1(const std::string& value);
  std::string* _internal_mutable_rectparams1();
  public:

  // bytes rectParams2 = 3;
  void clear_rectparams2();
  const std::string& rectparams2() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_rectparams2(ArgT0&& arg0, ArgT... args);
  std::string* mutable_rectparams2();
  PROTOBUF_NODISCARD std::string* release_rectparams2();
  void set_allocated_rectparams2(std::string* rectparams2);
  private:
  const std::string& _internal_rectparams2() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_rectparams2(const std::string& value);
  std::string* _internal_mutable_rectparams2();
  public:

  // sint32 xpcfGrpcReturnValue = 4;
  void clear_xpcfgrpcreturnvalue();
  int32_t xpcfgrpcreturnvalue() const;
  void set_xpcfgrpcreturnvalue(int32_t value);
  private:
  int32_t _internal_xpcfgrpcreturnvalue() const;
  void _internal_set_xpcfgrpcreturnvalue(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:grpcIStereoCameraCalibration.calibrateResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr transformation_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr rectparams1_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr rectparams2_;
    int32_t xpcfgrpcreturnvalue_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_grpcIStereoCameraCalibrationService_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// calibrateRequest

// int32 grpcServerCompressionFormat = 1;
inline void calibrateRequest::clear_grpcservercompressionformat() {
  _impl_.grpcservercompressionformat_ = 0;
}
inline int32_t calibrateRequest::_internal_grpcservercompressionformat() const {
  return _impl_.grpcservercompressionformat_;
}
inline int32_t calibrateRequest::grpcservercompressionformat() const {
  // @@protoc_insertion_point(field_get:grpcIStereoCameraCalibration.calibrateRequest.grpcServerCompressionFormat)
  return _internal_grpcservercompressionformat();
}
inline void calibrateRequest::_internal_set_grpcservercompressionformat(int32_t value) {
  
  _impl_.grpcservercompressionformat_ = value;
}
inline void calibrateRequest::set_grpcservercompressionformat(int32_t value) {
  _internal_set_grpcservercompressionformat(value);
  // @@protoc_insertion_point(field_set:grpcIStereoCameraCalibration.calibrateRequest.grpcServerCompressionFormat)
}

// bytes images1 = 2;
inline void calibrateRequest::clear_images1() {
  _impl_.images1_.ClearToEmpty();
}
inline const std::string& calibrateRequest::images1() const {
  // @@protoc_insertion_point(field_get:grpcIStereoCameraCalibration.calibrateRequest.images1)
  return _internal_images1();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void calibrateRequest::set_images1(ArgT0&& arg0, ArgT... args) {
 
 _impl_.images1_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:grpcIStereoCameraCalibration.calibrateRequest.images1)
}
inline std::string* calibrateRequest::mutable_images1() {
  std::string* _s = _internal_mutable_images1();
  // @@protoc_insertion_point(field_mutable:grpcIStereoCameraCalibration.calibrateRequest.images1)
  return _s;
}
inline const std::string& calibrateRequest::_internal_images1() const {
  return _impl_.images1_.Get();
}
inline void calibrateRequest::_internal_set_images1(const std::string& value) {
  
  _impl_.images1_.Set(value, GetArenaForAllocation());
}
inline std::string* calibrateRequest::_internal_mutable_images1() {
  
  return _impl_.images1_.Mutable(GetArenaForAllocation());
}
inline std::string* calibrateRequest::release_images1() {
  // @@protoc_insertion_point(field_release:grpcIStereoCameraCalibration.calibrateRequest.images1)
  return _impl_.images1_.Release();
}
inline void calibrateRequest::set_allocated_images1(std::string* images1) {
  if (images1 != nullptr) {
    
  } else {
    
  }
  _impl_.images1_.SetAllocated(images1, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.images1_.IsDefault()) {
    _impl_.images1_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:grpcIStereoCameraCalibration.calibrateRequest.images1)
}

// bytes images2 = 3;
inline void calibrateRequest::clear_images2() {
  _impl_.images2_.ClearToEmpty();
}
inline const std::string& calibrateRequest::images2() const {
  // @@protoc_insertion_point(field_get:grpcIStereoCameraCalibration.calibrateRequest.images2)
  return _internal_images2();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void calibrateRequest::set_images2(ArgT0&& arg0, ArgT... args) {
 
 _impl_.images2_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:grpcIStereoCameraCalibration.calibrateRequest.images2)
}
inline std::string* calibrateRequest::mutable_images2() {
  std::string* _s = _internal_mutable_images2();
  // @@protoc_insertion_point(field_mutable:grpcIStereoCameraCalibration.calibrateRequest.images2)
  return _s;
}
inline const std::string& calibrateRequest::_internal_images2() const {
  return _impl_.images2_.Get();
}
inline void calibrateRequest::_internal_set_images2(const std::string& value) {
  
  _impl_.images2_.Set(value, GetArenaForAllocation());
}
inline std::string* calibrateRequest::_internal_mutable_images2() {
  
  return _impl_.images2_.Mutable(GetArenaForAllocation());
}
inline std::string* calibrateRequest::release_images2() {
  // @@protoc_insertion_point(field_release:grpcIStereoCameraCalibration.calibrateRequest.images2)
  return _impl_.images2_.Release();
}
inline void calibrateRequest::set_allocated_images2(std::string* images2) {
  if (images2 != nullptr) {
    
  } else {
    
  }
  _impl_.images2_.SetAllocated(images2, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.images2_.IsDefault()) {
    _impl_.images2_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:grpcIStereoCameraCalibration.calibrateRequest.images2)
}

// bytes camParams1 = 4;
inline void calibrateRequest::clear_camparams1() {
  _impl_.camparams1_.ClearToEmpty();
}
inline const std::string& calibrateRequest::camparams1() const {
  // @@protoc_insertion_point(field_get:grpcIStereoCameraCalibration.calibrateRequest.camParams1)
  return _internal_camparams1();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void calibrateRequest::set_camparams1(ArgT0&& arg0, ArgT... args) {
 
 _impl_.camparams1_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:grpcIStereoCameraCalibration.calibrateRequest.camParams1)
}
inline std::string* calibrateRequest::mutable_camparams1() {
  std::string* _s = _internal_mutable_camparams1();
  // @@protoc_insertion_point(field_mutable:grpcIStereoCameraCalibration.calibrateRequest.camParams1)
  return _s;
}
inline const std::string& calibrateRequest::_internal_camparams1() const {
  return _impl_.camparams1_.Get();
}
inline void calibrateRequest::_internal_set_camparams1(const std::string& value) {
  
  _impl_.camparams1_.Set(value, GetArenaForAllocation());
}
inline std::string* calibrateRequest::_internal_mutable_camparams1() {
  
  return _impl_.camparams1_.Mutable(GetArenaForAllocation());
}
inline std::string* calibrateRequest::release_camparams1() {
  // @@protoc_insertion_point(field_release:grpcIStereoCameraCalibration.calibrateRequest.camParams1)
  return _impl_.camparams1_.Release();
}
inline void calibrateRequest::set_allocated_camparams1(std::string* camparams1) {
  if (camparams1 != nullptr) {
    
  } else {
    
  }
  _impl_.camparams1_.SetAllocated(camparams1, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.camparams1_.IsDefault()) {
    _impl_.camparams1_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:grpcIStereoCameraCalibration.calibrateRequest.camParams1)
}

// bytes camParams2 = 5;
inline void calibrateRequest::clear_camparams2() {
  _impl_.camparams2_.ClearToEmpty();
}
inline const std::string& calibrateRequest::camparams2() const {
  // @@protoc_insertion_point(field_get:grpcIStereoCameraCalibration.calibrateRequest.camParams2)
  return _internal_camparams2();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void calibrateRequest::set_camparams2(ArgT0&& arg0, ArgT... args) {
 
 _impl_.camparams2_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:grpcIStereoCameraCalibration.calibrateRequest.camParams2)
}
inline std::string* calibrateRequest::mutable_camparams2() {
  std::string* _s = _internal_mutable_camparams2();
  // @@protoc_insertion_point(field_mutable:grpcIStereoCameraCalibration.calibrateRequest.camParams2)
  return _s;
}
inline const std::string& calibrateRequest::_internal_camparams2() const {
  return _impl_.camparams2_.Get();
}
inline void calibrateRequest::_internal_set_camparams2(const std::string& value) {
  
  _impl_.camparams2_.Set(value, GetArenaForAllocation());
}
inline std::string* calibrateRequest::_internal_mutable_camparams2() {
  
  return _impl_.camparams2_.Mutable(GetArenaForAllocation());
}
inline std::string* calibrateRequest::release_camparams2() {
  // @@protoc_insertion_point(field_release:grpcIStereoCameraCalibration.calibrateRequest.camParams2)
  return _impl_.camparams2_.Release();
}
inline void calibrateRequest::set_allocated_camparams2(std::string* camparams2) {
  if (camparams2 != nullptr) {
    
  } else {
    
  }
  _impl_.camparams2_.SetAllocated(camparams2, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.camparams2_.IsDefault()) {
    _impl_.camparams2_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:grpcIStereoCameraCalibration.calibrateRequest.camParams2)
}

// bytes transformation = 6;
inline void calibrateRequest::clear_transformation() {
  _impl_.transformation_.ClearToEmpty();
}
inline const std::string& calibrateRequest::transformation() const {
  // @@protoc_insertion_point(field_get:grpcIStereoCameraCalibration.calibrateRequest.transformation)
  return _internal_transformation();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void calibrateRequest::set_transformation(ArgT0&& arg0, ArgT... args) {
 
 _impl_.transformation_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:grpcIStereoCameraCalibration.calibrateRequest.transformation)
}
inline std::string* calibrateRequest::mutable_transformation() {
  std::string* _s = _internal_mutable_transformation();
  // @@protoc_insertion_point(field_mutable:grpcIStereoCameraCalibration.calibrateRequest.transformation)
  return _s;
}
inline const std::string& calibrateRequest::_internal_transformation() const {
  return _impl_.transformation_.Get();
}
inline void calibrateRequest::_internal_set_transformation(const std::string& value) {
  
  _impl_.transformation_.Set(value, GetArenaForAllocation());
}
inline std::string* calibrateRequest::_internal_mutable_transformation() {
  
  return _impl_.transformation_.Mutable(GetArenaForAllocation());
}
inline std::string* calibrateRequest::release_transformation() {
  // @@protoc_insertion_point(field_release:grpcIStereoCameraCalibration.calibrateRequest.transformation)
  return _impl_.transformation_.Release();
}
inline void calibrateRequest::set_allocated_transformation(std::string* transformation) {
  if (transformation != nullptr) {
    
  } else {
    
  }
  _impl_.transformation_.SetAllocated(transformation, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.transformation_.IsDefault()) {
    _impl_.transformation_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:grpcIStereoCameraCalibration.calibrateRequest.transformation)
}

// bytes rectParams1 = 7;
inline void calibrateRequest::clear_rectparams1() {
  _impl_.rectparams1_.ClearToEmpty();
}
inline const std::string& calibrateRequest::rectparams1() const {
  // @@protoc_insertion_point(field_get:grpcIStereoCameraCalibration.calibrateRequest.rectParams1)
  return _internal_rectparams1();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void calibrateRequest::set_rectparams1(ArgT0&& arg0, ArgT... args) {
 
 _impl_.rectparams1_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:grpcIStereoCameraCalibration.calibrateRequest.rectParams1)
}
inline std::string* calibrateRequest::mutable_rectparams1() {
  std::string* _s = _internal_mutable_rectparams1();
  // @@protoc_insertion_point(field_mutable:grpcIStereoCameraCalibration.calibrateRequest.rectParams1)
  return _s;
}
inline const std::string& calibrateRequest::_internal_rectparams1() const {
  return _impl_.rectparams1_.Get();
}
inline void calibrateRequest::_internal_set_rectparams1(const std::string& value) {
  
  _impl_.rectparams1_.Set(value, GetArenaForAllocation());
}
inline std::string* calibrateRequest::_internal_mutable_rectparams1() {
  
  return _impl_.rectparams1_.Mutable(GetArenaForAllocation());
}
inline std::string* calibrateRequest::release_rectparams1() {
  // @@protoc_insertion_point(field_release:grpcIStereoCameraCalibration.calibrateRequest.rectParams1)
  return _impl_.rectparams1_.Release();
}
inline void calibrateRequest::set_allocated_rectparams1(std::string* rectparams1) {
  if (rectparams1 != nullptr) {
    
  } else {
    
  }
  _impl_.rectparams1_.SetAllocated(rectparams1, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.rectparams1_.IsDefault()) {
    _impl_.rectparams1_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:grpcIStereoCameraCalibration.calibrateRequest.rectParams1)
}

// bytes rectParams2 = 8;
inline void calibrateRequest::clear_rectparams2() {
  _impl_.rectparams2_.ClearToEmpty();
}
inline const std::string& calibrateRequest::rectparams2() const {
  // @@protoc_insertion_point(field_get:grpcIStereoCameraCalibration.calibrateRequest.rectParams2)
  return _internal_rectparams2();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void calibrateRequest::set_rectparams2(ArgT0&& arg0, ArgT... args) {
 
 _impl_.rectparams2_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:grpcIStereoCameraCalibration.calibrateRequest.rectParams2)
}
inline std::string* calibrateRequest::mutable_rectparams2() {
  std::string* _s = _internal_mutable_rectparams2();
  // @@protoc_insertion_point(field_mutable:grpcIStereoCameraCalibration.calibrateRequest.rectParams2)
  return _s;
}
inline const std::string& calibrateRequest::_internal_rectparams2() const {
  return _impl_.rectparams2_.Get();
}
inline void calibrateRequest::_internal_set_rectparams2(const std::string& value) {
  
  _impl_.rectparams2_.Set(value, GetArenaForAllocation());
}
inline std::string* calibrateRequest::_internal_mutable_rectparams2() {
  
  return _impl_.rectparams2_.Mutable(GetArenaForAllocation());
}
inline std::string* calibrateRequest::release_rectparams2() {
  // @@protoc_insertion_point(field_release:grpcIStereoCameraCalibration.calibrateRequest.rectParams2)
  return _impl_.rectparams2_.Release();
}
inline void calibrateRequest::set_allocated_rectparams2(std::string* rectparams2) {
  if (rectparams2 != nullptr) {
    
  } else {
    
  }
  _impl_.rectparams2_.SetAllocated(rectparams2, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.rectparams2_.IsDefault()) {
    _impl_.rectparams2_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:grpcIStereoCameraCalibration.calibrateRequest.rectParams2)
}

// -------------------------------------------------------------------

// calibrateResponse

// bytes transformation = 1;
inline void calibrateResponse::clear_transformation() {
  _impl_.transformation_.ClearToEmpty();
}
inline const std::string& calibrateResponse::transformation() const {
  // @@protoc_insertion_point(field_get:grpcIStereoCameraCalibration.calibrateResponse.transformation)
  return _internal_transformation();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void calibrateResponse::set_transformation(ArgT0&& arg0, ArgT... args) {
 
 _impl_.transformation_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:grpcIStereoCameraCalibration.calibrateResponse.transformation)
}
inline std::string* calibrateResponse::mutable_transformation() {
  std::string* _s = _internal_mutable_transformation();
  // @@protoc_insertion_point(field_mutable:grpcIStereoCameraCalibration.calibrateResponse.transformation)
  return _s;
}
inline const std::string& calibrateResponse::_internal_transformation() const {
  return _impl_.transformation_.Get();
}
inline void calibrateResponse::_internal_set_transformation(const std::string& value) {
  
  _impl_.transformation_.Set(value, GetArenaForAllocation());
}
inline std::string* calibrateResponse::_internal_mutable_transformation() {
  
  return _impl_.transformation_.Mutable(GetArenaForAllocation());
}
inline std::string* calibrateResponse::release_transformation() {
  // @@protoc_insertion_point(field_release:grpcIStereoCameraCalibration.calibrateResponse.transformation)
  return _impl_.transformation_.Release();
}
inline void calibrateResponse::set_allocated_transformation(std::string* transformation) {
  if (transformation != nullptr) {
    
  } else {
    
  }
  _impl_.transformation_.SetAllocated(transformation, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.transformation_.IsDefault()) {
    _impl_.transformation_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:grpcIStereoCameraCalibration.calibrateResponse.transformation)
}

// bytes rectParams1 = 2;
inline void calibrateResponse::clear_rectparams1() {
  _impl_.rectparams1_.ClearToEmpty();
}
inline const std::string& calibrateResponse::rectparams1() const {
  // @@protoc_insertion_point(field_get:grpcIStereoCameraCalibration.calibrateResponse.rectParams1)
  return _internal_rectparams1();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void calibrateResponse::set_rectparams1(ArgT0&& arg0, ArgT... args) {
 
 _impl_.rectparams1_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:grpcIStereoCameraCalibration.calibrateResponse.rectParams1)
}
inline std::string* calibrateResponse::mutable_rectparams1() {
  std::string* _s = _internal_mutable_rectparams1();
  // @@protoc_insertion_point(field_mutable:grpcIStereoCameraCalibration.calibrateResponse.rectParams1)
  return _s;
}
inline const std::string& calibrateResponse::_internal_rectparams1() const {
  return _impl_.rectparams1_.Get();
}
inline void calibrateResponse::_internal_set_rectparams1(const std::string& value) {
  
  _impl_.rectparams1_.Set(value, GetArenaForAllocation());
}
inline std::string* calibrateResponse::_internal_mutable_rectparams1() {
  
  return _impl_.rectparams1_.Mutable(GetArenaForAllocation());
}
inline std::string* calibrateResponse::release_rectparams1() {
  // @@protoc_insertion_point(field_release:grpcIStereoCameraCalibration.calibrateResponse.rectParams1)
  return _impl_.rectparams1_.Release();
}
inline void calibrateResponse::set_allocated_rectparams1(std::string* rectparams1) {
  if (rectparams1 != nullptr) {
    
  } else {
    
  }
  _impl_.rectparams1_.SetAllocated(rectparams1, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.rectparams1_.IsDefault()) {
    _impl_.rectparams1_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:grpcIStereoCameraCalibration.calibrateResponse.rectParams1)
}

// bytes rectParams2 = 3;
inline void calibrateResponse::clear_rectparams2() {
  _impl_.rectparams2_.ClearToEmpty();
}
inline const std::string& calibrateResponse::rectparams2() const {
  // @@protoc_insertion_point(field_get:grpcIStereoCameraCalibration.calibrateResponse.rectParams2)
  return _internal_rectparams2();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void calibrateResponse::set_rectparams2(ArgT0&& arg0, ArgT... args) {
 
 _impl_.rectparams2_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:grpcIStereoCameraCalibration.calibrateResponse.rectParams2)
}
inline std::string* calibrateResponse::mutable_rectparams2() {
  std::string* _s = _internal_mutable_rectparams2();
  // @@protoc_insertion_point(field_mutable:grpcIStereoCameraCalibration.calibrateResponse.rectParams2)
  return _s;
}
inline const std::string& calibrateResponse::_internal_rectparams2() const {
  return _impl_.rectparams2_.Get();
}
inline void calibrateResponse::_internal_set_rectparams2(const std::string& value) {
  
  _impl_.rectparams2_.Set(value, GetArenaForAllocation());
}
inline std::string* calibrateResponse::_internal_mutable_rectparams2() {
  
  return _impl_.rectparams2_.Mutable(GetArenaForAllocation());
}
inline std::string* calibrateResponse::release_rectparams2() {
  // @@protoc_insertion_point(field_release:grpcIStereoCameraCalibration.calibrateResponse.rectParams2)
  return _impl_.rectparams2_.Release();
}
inline void calibrateResponse::set_allocated_rectparams2(std::string* rectparams2) {
  if (rectparams2 != nullptr) {
    
  } else {
    
  }
  _impl_.rectparams2_.SetAllocated(rectparams2, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.rectparams2_.IsDefault()) {
    _impl_.rectparams2_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:grpcIStereoCameraCalibration.calibrateResponse.rectParams2)
}

// sint32 xpcfGrpcReturnValue = 4;
inline void calibrateResponse::clear_xpcfgrpcreturnvalue() {
  _impl_.xpcfgrpcreturnvalue_ = 0;
}
inline int32_t calibrateResponse::_internal_xpcfgrpcreturnvalue() const {
  return _impl_.xpcfgrpcreturnvalue_;
}
inline int32_t calibrateResponse::xpcfgrpcreturnvalue() const {
  // @@protoc_insertion_point(field_get:grpcIStereoCameraCalibration.calibrateResponse.xpcfGrpcReturnValue)
  return _internal_xpcfgrpcreturnvalue();
}
inline void calibrateResponse::_internal_set_xpcfgrpcreturnvalue(int32_t value) {
  
  _impl_.xpcfgrpcreturnvalue_ = value;
}
inline void calibrateResponse::set_xpcfgrpcreturnvalue(int32_t value) {
  _internal_set_xpcfgrpcreturnvalue(value);
  // @@protoc_insertion_point(field_set:grpcIStereoCameraCalibration.calibrateResponse.xpcfGrpcReturnValue)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace grpcIStereoCameraCalibration

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_grpcIStereoCameraCalibrationService_2eproto
