// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: grpcIImageFilterService.proto

#include "grpcIImageFilterService.pb.h"
#include "grpcIImageFilterService.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace grpcIImageFilter {

static const char* grpcIImageFilterService_method_names[] = {
  "/grpcIImageFilter.grpcIImageFilterService/filter",
};

std::unique_ptr< grpcIImageFilterService::Stub> grpcIImageFilterService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< grpcIImageFilterService::Stub> stub(new grpcIImageFilterService::Stub(channel, options));
  return stub;
}

grpcIImageFilterService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_filter_(grpcIImageFilterService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status grpcIImageFilterService::Stub::filter(::grpc::ClientContext* context, const ::grpcIImageFilter::filterRequest& request, ::grpcIImageFilter::filterResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::grpcIImageFilter::filterRequest, ::grpcIImageFilter::filterResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_filter_, context, request, response);
}

void grpcIImageFilterService::Stub::async::filter(::grpc::ClientContext* context, const ::grpcIImageFilter::filterRequest* request, ::grpcIImageFilter::filterResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::grpcIImageFilter::filterRequest, ::grpcIImageFilter::filterResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_filter_, context, request, response, std::move(f));
}

void grpcIImageFilterService::Stub::async::filter(::grpc::ClientContext* context, const ::grpcIImageFilter::filterRequest* request, ::grpcIImageFilter::filterResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_filter_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::grpcIImageFilter::filterResponse>* grpcIImageFilterService::Stub::PrepareAsyncfilterRaw(::grpc::ClientContext* context, const ::grpcIImageFilter::filterRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::grpcIImageFilter::filterResponse, ::grpcIImageFilter::filterRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_filter_, context, request);
}

::grpc::ClientAsyncResponseReader< ::grpcIImageFilter::filterResponse>* grpcIImageFilterService::Stub::AsyncfilterRaw(::grpc::ClientContext* context, const ::grpcIImageFilter::filterRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncfilterRaw(context, request, cq);
  result->StartCall();
  return result;
}

grpcIImageFilterService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      grpcIImageFilterService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< grpcIImageFilterService::Service, ::grpcIImageFilter::filterRequest, ::grpcIImageFilter::filterResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](grpcIImageFilterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::grpcIImageFilter::filterRequest* req,
             ::grpcIImageFilter::filterResponse* resp) {
               return service->filter(ctx, req, resp);
             }, this)));
}

grpcIImageFilterService::Service::~Service() {
}

::grpc::Status grpcIImageFilterService::Service::filter(::grpc::ServerContext* context, const ::grpcIImageFilter::filterRequest* request, ::grpcIImageFilter::filterResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace grpcIImageFilter

