// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: grpcICameraCalibrationService.proto
#ifndef GRPC_grpcICameraCalibrationService_2eproto__INCLUDED
#define GRPC_grpcICameraCalibrationService_2eproto__INCLUDED

#include "grpcICameraCalibrationService.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpcICameraCalibration {

class grpcICameraCalibrationService final {
 public:
  static constexpr char const* service_full_name() {
    return "grpcICameraCalibration.grpcICameraCalibrationService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status calibrate(::grpc::ClientContext* context, const ::grpcICameraCalibration::calibrateRequest& request, ::grpcICameraCalibration::calibrateResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpcICameraCalibration::calibrateResponse>> Asynccalibrate(::grpc::ClientContext* context, const ::grpcICameraCalibration::calibrateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpcICameraCalibration::calibrateResponse>>(AsynccalibrateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpcICameraCalibration::calibrateResponse>> PrepareAsynccalibrate(::grpc::ClientContext* context, const ::grpcICameraCalibration::calibrateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpcICameraCalibration::calibrateResponse>>(PrepareAsynccalibrateRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void calibrate(::grpc::ClientContext* context, const ::grpcICameraCalibration::calibrateRequest* request, ::grpcICameraCalibration::calibrateResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void calibrate(::grpc::ClientContext* context, const ::grpcICameraCalibration::calibrateRequest* request, ::grpcICameraCalibration::calibrateResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::grpcICameraCalibration::calibrateResponse>* AsynccalibrateRaw(::grpc::ClientContext* context, const ::grpcICameraCalibration::calibrateRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::grpcICameraCalibration::calibrateResponse>* PrepareAsynccalibrateRaw(::grpc::ClientContext* context, const ::grpcICameraCalibration::calibrateRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status calibrate(::grpc::ClientContext* context, const ::grpcICameraCalibration::calibrateRequest& request, ::grpcICameraCalibration::calibrateResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpcICameraCalibration::calibrateResponse>> Asynccalibrate(::grpc::ClientContext* context, const ::grpcICameraCalibration::calibrateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpcICameraCalibration::calibrateResponse>>(AsynccalibrateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpcICameraCalibration::calibrateResponse>> PrepareAsynccalibrate(::grpc::ClientContext* context, const ::grpcICameraCalibration::calibrateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpcICameraCalibration::calibrateResponse>>(PrepareAsynccalibrateRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void calibrate(::grpc::ClientContext* context, const ::grpcICameraCalibration::calibrateRequest* request, ::grpcICameraCalibration::calibrateResponse* response, std::function<void(::grpc::Status)>) override;
      void calibrate(::grpc::ClientContext* context, const ::grpcICameraCalibration::calibrateRequest* request, ::grpcICameraCalibration::calibrateResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::grpcICameraCalibration::calibrateResponse>* AsynccalibrateRaw(::grpc::ClientContext* context, const ::grpcICameraCalibration::calibrateRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::grpcICameraCalibration::calibrateResponse>* PrepareAsynccalibrateRaw(::grpc::ClientContext* context, const ::grpcICameraCalibration::calibrateRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_calibrate_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status calibrate(::grpc::ServerContext* context, const ::grpcICameraCalibration::calibrateRequest* request, ::grpcICameraCalibration::calibrateResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_calibrate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_calibrate() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_calibrate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status calibrate(::grpc::ServerContext* /*context*/, const ::grpcICameraCalibration::calibrateRequest* /*request*/, ::grpcICameraCalibration::calibrateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestcalibrate(::grpc::ServerContext* context, ::grpcICameraCalibration::calibrateRequest* request, ::grpc::ServerAsyncResponseWriter< ::grpcICameraCalibration::calibrateResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_calibrate<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_calibrate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_calibrate() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpcICameraCalibration::calibrateRequest, ::grpcICameraCalibration::calibrateResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpcICameraCalibration::calibrateRequest* request, ::grpcICameraCalibration::calibrateResponse* response) { return this->calibrate(context, request, response); }));}
    void SetMessageAllocatorFor_calibrate(
        ::grpc::MessageAllocator< ::grpcICameraCalibration::calibrateRequest, ::grpcICameraCalibration::calibrateResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::grpcICameraCalibration::calibrateRequest, ::grpcICameraCalibration::calibrateResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_calibrate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status calibrate(::grpc::ServerContext* /*context*/, const ::grpcICameraCalibration::calibrateRequest* /*request*/, ::grpcICameraCalibration::calibrateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* calibrate(
      ::grpc::CallbackServerContext* /*context*/, const ::grpcICameraCalibration::calibrateRequest* /*request*/, ::grpcICameraCalibration::calibrateResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_calibrate<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_calibrate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_calibrate() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_calibrate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status calibrate(::grpc::ServerContext* /*context*/, const ::grpcICameraCalibration::calibrateRequest* /*request*/, ::grpcICameraCalibration::calibrateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_calibrate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_calibrate() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_calibrate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status calibrate(::grpc::ServerContext* /*context*/, const ::grpcICameraCalibration::calibrateRequest* /*request*/, ::grpcICameraCalibration::calibrateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestcalibrate(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_calibrate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_calibrate() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->calibrate(context, request, response); }));
    }
    ~WithRawCallbackMethod_calibrate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status calibrate(::grpc::ServerContext* /*context*/, const ::grpcICameraCalibration::calibrateRequest* /*request*/, ::grpcICameraCalibration::calibrateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* calibrate(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_calibrate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_calibrate() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::grpcICameraCalibration::calibrateRequest, ::grpcICameraCalibration::calibrateResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::grpcICameraCalibration::calibrateRequest, ::grpcICameraCalibration::calibrateResponse>* streamer) {
                       return this->Streamedcalibrate(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_calibrate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status calibrate(::grpc::ServerContext* /*context*/, const ::grpcICameraCalibration::calibrateRequest* /*request*/, ::grpcICameraCalibration::calibrateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedcalibrate(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::grpcICameraCalibration::calibrateRequest,::grpcICameraCalibration::calibrateResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_calibrate<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_calibrate<Service > StreamedService;
};

}  // namespace grpcICameraCalibration


#endif  // GRPC_grpcICameraCalibrationService_2eproto__INCLUDED
