// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: grpcIPCFilterCentroidService.proto
#ifndef GRPC_grpcIPCFilterCentroidService_2eproto__INCLUDED
#define GRPC_grpcIPCFilterCentroidService_2eproto__INCLUDED

#include "grpcIPCFilterCentroidService.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpcIPCFilterCentroid {

class grpcIPCFilterCentroidService final {
 public:
  static constexpr char const* service_full_name() {
    return "grpcIPCFilterCentroid.grpcIPCFilterCentroidService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status filter(::grpc::ClientContext* context, const ::grpcIPCFilterCentroid::filterRequest& request, ::grpcIPCFilterCentroid::filterResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpcIPCFilterCentroid::filterResponse>> Asyncfilter(::grpc::ClientContext* context, const ::grpcIPCFilterCentroid::filterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpcIPCFilterCentroid::filterResponse>>(AsyncfilterRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpcIPCFilterCentroid::filterResponse>> PrepareAsyncfilter(::grpc::ClientContext* context, const ::grpcIPCFilterCentroid::filterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpcIPCFilterCentroid::filterResponse>>(PrepareAsyncfilterRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void filter(::grpc::ClientContext* context, const ::grpcIPCFilterCentroid::filterRequest* request, ::grpcIPCFilterCentroid::filterResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void filter(::grpc::ClientContext* context, const ::grpcIPCFilterCentroid::filterRequest* request, ::grpcIPCFilterCentroid::filterResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::grpcIPCFilterCentroid::filterResponse>* AsyncfilterRaw(::grpc::ClientContext* context, const ::grpcIPCFilterCentroid::filterRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::grpcIPCFilterCentroid::filterResponse>* PrepareAsyncfilterRaw(::grpc::ClientContext* context, const ::grpcIPCFilterCentroid::filterRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status filter(::grpc::ClientContext* context, const ::grpcIPCFilterCentroid::filterRequest& request, ::grpcIPCFilterCentroid::filterResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpcIPCFilterCentroid::filterResponse>> Asyncfilter(::grpc::ClientContext* context, const ::grpcIPCFilterCentroid::filterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpcIPCFilterCentroid::filterResponse>>(AsyncfilterRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpcIPCFilterCentroid::filterResponse>> PrepareAsyncfilter(::grpc::ClientContext* context, const ::grpcIPCFilterCentroid::filterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpcIPCFilterCentroid::filterResponse>>(PrepareAsyncfilterRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void filter(::grpc::ClientContext* context, const ::grpcIPCFilterCentroid::filterRequest* request, ::grpcIPCFilterCentroid::filterResponse* response, std::function<void(::grpc::Status)>) override;
      void filter(::grpc::ClientContext* context, const ::grpcIPCFilterCentroid::filterRequest* request, ::grpcIPCFilterCentroid::filterResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::grpcIPCFilterCentroid::filterResponse>* AsyncfilterRaw(::grpc::ClientContext* context, const ::grpcIPCFilterCentroid::filterRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::grpcIPCFilterCentroid::filterResponse>* PrepareAsyncfilterRaw(::grpc::ClientContext* context, const ::grpcIPCFilterCentroid::filterRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_filter_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status filter(::grpc::ServerContext* context, const ::grpcIPCFilterCentroid::filterRequest* request, ::grpcIPCFilterCentroid::filterResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_filter : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_filter() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_filter() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status filter(::grpc::ServerContext* /*context*/, const ::grpcIPCFilterCentroid::filterRequest* /*request*/, ::grpcIPCFilterCentroid::filterResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestfilter(::grpc::ServerContext* context, ::grpcIPCFilterCentroid::filterRequest* request, ::grpc::ServerAsyncResponseWriter< ::grpcIPCFilterCentroid::filterResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_filter<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_filter : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_filter() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpcIPCFilterCentroid::filterRequest, ::grpcIPCFilterCentroid::filterResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpcIPCFilterCentroid::filterRequest* request, ::grpcIPCFilterCentroid::filterResponse* response) { return this->filter(context, request, response); }));}
    void SetMessageAllocatorFor_filter(
        ::grpc::MessageAllocator< ::grpcIPCFilterCentroid::filterRequest, ::grpcIPCFilterCentroid::filterResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::grpcIPCFilterCentroid::filterRequest, ::grpcIPCFilterCentroid::filterResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_filter() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status filter(::grpc::ServerContext* /*context*/, const ::grpcIPCFilterCentroid::filterRequest* /*request*/, ::grpcIPCFilterCentroid::filterResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* filter(
      ::grpc::CallbackServerContext* /*context*/, const ::grpcIPCFilterCentroid::filterRequest* /*request*/, ::grpcIPCFilterCentroid::filterResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_filter<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_filter : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_filter() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_filter() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status filter(::grpc::ServerContext* /*context*/, const ::grpcIPCFilterCentroid::filterRequest* /*request*/, ::grpcIPCFilterCentroid::filterResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_filter : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_filter() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_filter() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status filter(::grpc::ServerContext* /*context*/, const ::grpcIPCFilterCentroid::filterRequest* /*request*/, ::grpcIPCFilterCentroid::filterResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestfilter(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_filter : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_filter() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->filter(context, request, response); }));
    }
    ~WithRawCallbackMethod_filter() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status filter(::grpc::ServerContext* /*context*/, const ::grpcIPCFilterCentroid::filterRequest* /*request*/, ::grpcIPCFilterCentroid::filterResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* filter(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_filter : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_filter() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::grpcIPCFilterCentroid::filterRequest, ::grpcIPCFilterCentroid::filterResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::grpcIPCFilterCentroid::filterRequest, ::grpcIPCFilterCentroid::filterResponse>* streamer) {
                       return this->Streamedfilter(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_filter() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status filter(::grpc::ServerContext* /*context*/, const ::grpcIPCFilterCentroid::filterRequest* /*request*/, ::grpcIPCFilterCentroid::filterResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedfilter(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::grpcIPCFilterCentroid::filterRequest,::grpcIPCFilterCentroid::filterResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_filter<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_filter<Service > StreamedService;
};

}  // namespace grpcIPCFilterCentroid


#endif  // GRPC_grpcIPCFilterCentroidService_2eproto__INCLUDED
