
HEADERS += \
IAsyncRelocalizationPipeline_grpcProxy.h \
IAsyncRelocalizationPipeline_grpcServer.h \
grpcIAsyncRelocalizationPipelineService.pb.h \
grpcIAsyncRelocalizationPipelineService.grpc.pb.h \
IMapUpdatePipeline_grpcProxy.h \
IMapUpdatePipeline_grpcServer.h \
grpcIMapUpdatePipelineService.pb.h \
grpcIMapUpdatePipelineService.grpc.pb.h \
IMappingPipeline_grpcProxy.h \
IMappingPipeline_grpcServer.h \
grpcIMappingPipelineService.pb.h \
grpcIMappingPipelineService.grpc.pb.h \
IRelocalizationPipeline_grpcProxy.h \
IRelocalizationPipeline_grpcServer.h \
grpcIRelocalizationPipelineService.pb.h \
grpcIRelocalizationPipelineService.grpc.pb.h \
IPCFilter_grpcProxy.h \
IPCFilter_grpcServer.h \
grpcIPCFilterService.pb.h \
grpcIPCFilterService.grpc.pb.h \
IPCFilterCentroid_grpcProxy.h \
IPCFilterCentroid_grpcServer.h \
grpcIPCFilterCentroidService.pb.h \
grpcIPCFilterCentroidService.grpc.pb.h \
IRegression_grpcProxy.h \
IRegression_grpcServer.h \
grpcIRegressionService.pb.h \
grpcIRegressionService.grpc.pb.h \
IRelocalizer_grpcProxy.h \
IRelocalizer_grpcServer.h \
grpcIRelocalizerService.pb.h \
grpcIRelocalizerService.grpc.pb.h \
IBootstrapper_grpcProxy.h \
IBootstrapper_grpcServer.h \
grpcIBootstrapperService.pb.h \
grpcIBootstrapperService.grpc.pb.h \
IMapping_grpcProxy.h \
IMapping_grpcServer.h \
grpcIMappingService.pb.h \
grpcIMappingService.grpc.pb.h \
ITracking_grpcProxy.h \
ITracking_grpcServer.h \
grpcITrackingService.pb.h \
grpcITrackingService.grpc.pb.h \
IBundler_grpcProxy.h \
IBundler_grpcServer.h \
grpcIBundlerService.pb.h \
grpcIBundlerService.grpc.pb.h \
IMapFilter_grpcProxy.h \
IMapFilter_grpcServer.h \
grpcIMapFilterService.pb.h \
grpcIMapFilterService.grpc.pb.h \
IMapUpdate_grpcProxy.h \
IMapUpdate_grpcServer.h \
grpcIMapUpdateService.pb.h \
grpcIMapUpdateService.grpc.pb.h \
ITriangulator_grpcProxy.h \
ITriangulator_grpcServer.h \
grpcITriangulatorService.pb.h \
grpcITriangulatorService.grpc.pb.h \
I2D3DCorrespondencesFinder_grpcProxy.h \
I2D3DCorrespondencesFinder_grpcServer.h \
grpcI2D3DCorrespondencesFinderService.pb.h \
grpcI2D3DCorrespondencesFinderService.grpc.pb.h \
I2DTransformFinder_grpcProxy.h \
I2DTransformFinder_grpcServer.h \
grpcI2DTransformFinderService.pb.h \
grpcI2DTransformFinderService.grpc.pb.h \
I2Dto3DTransformDecomposer_grpcProxy.h \
I2Dto3DTransformDecomposer_grpcServer.h \
grpcI2Dto3DTransformDecomposerService.pb.h \
grpcI2Dto3DTransformDecomposerService.grpc.pb.h \
I2Dto3DTransformDecomposerValidation_grpcProxy.h \
I2Dto3DTransformDecomposerValidation_grpcServer.h \
grpcI2Dto3DTransformDecomposerValidationService.pb.h \
grpcI2Dto3DTransformDecomposerValidationService.grpc.pb.h \
I3D3DCorrespondencesFinder_grpcProxy.h \
I3D3DCorrespondencesFinder_grpcServer.h \
grpcI3D3DCorrespondencesFinderService.pb.h \
grpcI3D3DCorrespondencesFinderService.grpc.pb.h \
I3DTransformFinderFrom2D2D_grpcProxy.h \
I3DTransformFinderFrom2D2D_grpcServer.h \
grpcI3DTransformFinderFrom2D2DService.pb.h \
grpcI3DTransformFinderFrom2D2DService.grpc.pb.h \
I3DTransformFinderFrom2D3D_grpcProxy.h \
I3DTransformFinderFrom2D3D_grpcServer.h \
grpcI3DTransformFinderFrom2D3DService.pb.h \
grpcI3DTransformFinderFrom2D3DService.grpc.pb.h \
I3DTransformFinderFrom3D3D_grpcProxy.h \
I3DTransformFinderFrom3D3D_grpcServer.h \
grpcI3DTransformFinderFrom3D3DService.pb.h \
grpcI3DTransformFinderFrom3D3DService.grpc.pb.h \
I3DTransformSACFinderFrom2D3D_grpcProxy.h \
I3DTransformSACFinderFrom2D3D_grpcServer.h \
grpcI3DTransformSACFinderFrom2D3DService.pb.h \
grpcI3DTransformSACFinderFrom2D3DService.grpc.pb.h \
I3DTransformSACFinderFrom3D3D_grpcProxy.h \
I3DTransformSACFinderFrom3D3D_grpcServer.h \
grpcI3DTransformSACFinderFrom3D3DService.pb.h \
grpcI3DTransformSACFinderFrom3D3DService.grpc.pb.h \
IHomographyValidation_grpcProxy.h \
IHomographyValidation_grpcServer.h \
grpcIHomographyValidationService.pb.h \
grpcIHomographyValidationService.grpc.pb.h \
ITrackablePose_grpcProxy.h \
ITrackablePose_grpcServer.h \
grpcITrackablePoseService.pb.h \
grpcITrackablePoseService.grpc.pb.h \
IMapManager_grpcProxy.h \
IMapManager_grpcServer.h \
grpcIMapManagerService.pb.h \
grpcIMapManagerService.grpc.pb.h \
IOpticalFlowEstimator_grpcProxy.h \
IOpticalFlowEstimator_grpcServer.h \
grpcIOpticalFlowEstimatorService.pb.h \
grpcIOpticalFlowEstimatorService.grpc.pb.h \
xpcfGrpcModuleMain.h

SOURCES += \
IAsyncRelocalizationPipeline_grpcProxy.cpp \
IAsyncRelocalizationPipeline_grpcServer.cpp \
grpcIAsyncRelocalizationPipelineService.pb.cc \
grpcIAsyncRelocalizationPipelineService.grpc.pb.cc \
IMapUpdatePipeline_grpcProxy.cpp \
IMapUpdatePipeline_grpcServer.cpp \
grpcIMapUpdatePipelineService.pb.cc \
grpcIMapUpdatePipelineService.grpc.pb.cc \
IMappingPipeline_grpcProxy.cpp \
IMappingPipeline_grpcServer.cpp \
grpcIMappingPipelineService.pb.cc \
grpcIMappingPipelineService.grpc.pb.cc \
IRelocalizationPipeline_grpcProxy.cpp \
IRelocalizationPipeline_grpcServer.cpp \
grpcIRelocalizationPipelineService.pb.cc \
grpcIRelocalizationPipelineService.grpc.pb.cc \
IPCFilter_grpcProxy.cpp \
IPCFilter_grpcServer.cpp \
grpcIPCFilterService.pb.cc \
grpcIPCFilterService.grpc.pb.cc \
IPCFilterCentroid_grpcProxy.cpp \
IPCFilterCentroid_grpcServer.cpp \
grpcIPCFilterCentroidService.pb.cc \
grpcIPCFilterCentroidService.grpc.pb.cc \
IRegression_grpcProxy.cpp \
IRegression_grpcServer.cpp \
grpcIRegressionService.pb.cc \
grpcIRegressionService.grpc.pb.cc \
IRelocalizer_grpcProxy.cpp \
IRelocalizer_grpcServer.cpp \
grpcIRelocalizerService.pb.cc \
grpcIRelocalizerService.grpc.pb.cc \
IBootstrapper_grpcProxy.cpp \
IBootstrapper_grpcServer.cpp \
grpcIBootstrapperService.pb.cc \
grpcIBootstrapperService.grpc.pb.cc \
IMapping_grpcProxy.cpp \
IMapping_grpcServer.cpp \
grpcIMappingService.pb.cc \
grpcIMappingService.grpc.pb.cc \
ITracking_grpcProxy.cpp \
ITracking_grpcServer.cpp \
grpcITrackingService.pb.cc \
grpcITrackingService.grpc.pb.cc \
IBundler_grpcProxy.cpp \
IBundler_grpcServer.cpp \
grpcIBundlerService.pb.cc \
grpcIBundlerService.grpc.pb.cc \
IMapFilter_grpcProxy.cpp \
IMapFilter_grpcServer.cpp \
grpcIMapFilterService.pb.cc \
grpcIMapFilterService.grpc.pb.cc \
IMapUpdate_grpcProxy.cpp \
IMapUpdate_grpcServer.cpp \
grpcIMapUpdateService.pb.cc \
grpcIMapUpdateService.grpc.pb.cc \
ITriangulator_grpcProxy.cpp \
ITriangulator_grpcServer.cpp \
grpcITriangulatorService.pb.cc \
grpcITriangulatorService.grpc.pb.cc \
I2D3DCorrespondencesFinder_grpcProxy.cpp \
I2D3DCorrespondencesFinder_grpcServer.cpp \
grpcI2D3DCorrespondencesFinderService.pb.cc \
grpcI2D3DCorrespondencesFinderService.grpc.pb.cc \
I2DTransformFinder_grpcProxy.cpp \
I2DTransformFinder_grpcServer.cpp \
grpcI2DTransformFinderService.pb.cc \
grpcI2DTransformFinderService.grpc.pb.cc \
I2Dto3DTransformDecomposer_grpcProxy.cpp \
I2Dto3DTransformDecomposer_grpcServer.cpp \
grpcI2Dto3DTransformDecomposerService.pb.cc \
grpcI2Dto3DTransformDecomposerService.grpc.pb.cc \
I2Dto3DTransformDecomposerValidation_grpcProxy.cpp \
I2Dto3DTransformDecomposerValidation_grpcServer.cpp \
grpcI2Dto3DTransformDecomposerValidationService.pb.cc \
grpcI2Dto3DTransformDecomposerValidationService.grpc.pb.cc \
I3D3DCorrespondencesFinder_grpcProxy.cpp \
I3D3DCorrespondencesFinder_grpcServer.cpp \
grpcI3D3DCorrespondencesFinderService.pb.cc \
grpcI3D3DCorrespondencesFinderService.grpc.pb.cc \
I3DTransformFinderFrom2D2D_grpcProxy.cpp \
I3DTransformFinderFrom2D2D_grpcServer.cpp \
grpcI3DTransformFinderFrom2D2DService.pb.cc \
grpcI3DTransformFinderFrom2D2DService.grpc.pb.cc \
I3DTransformFinderFrom2D3D_grpcProxy.cpp \
I3DTransformFinderFrom2D3D_grpcServer.cpp \
grpcI3DTransformFinderFrom2D3DService.pb.cc \
grpcI3DTransformFinderFrom2D3DService.grpc.pb.cc \
I3DTransformFinderFrom3D3D_grpcProxy.cpp \
I3DTransformFinderFrom3D3D_grpcServer.cpp \
grpcI3DTransformFinderFrom3D3DService.pb.cc \
grpcI3DTransformFinderFrom3D3DService.grpc.pb.cc \
I3DTransformSACFinderFrom2D3D_grpcProxy.cpp \
I3DTransformSACFinderFrom2D3D_grpcServer.cpp \
grpcI3DTransformSACFinderFrom2D3DService.pb.cc \
grpcI3DTransformSACFinderFrom2D3DService.grpc.pb.cc \
I3DTransformSACFinderFrom3D3D_grpcProxy.cpp \
I3DTransformSACFinderFrom3D3D_grpcServer.cpp \
grpcI3DTransformSACFinderFrom3D3DService.pb.cc \
grpcI3DTransformSACFinderFrom3D3DService.grpc.pb.cc \
IHomographyValidation_grpcProxy.cpp \
IHomographyValidation_grpcServer.cpp \
grpcIHomographyValidationService.pb.cc \
grpcIHomographyValidationService.grpc.pb.cc \
ITrackablePose_grpcProxy.cpp \
ITrackablePose_grpcServer.cpp \
grpcITrackablePoseService.pb.cc \
grpcITrackablePoseService.grpc.pb.cc \
IMapManager_grpcProxy.cpp \
IMapManager_grpcServer.cpp \
grpcIMapManagerService.pb.cc \
grpcIMapManagerService.grpc.pb.cc \
IOpticalFlowEstimator_grpcProxy.cpp \
IOpticalFlowEstimator_grpcServer.cpp \
grpcIOpticalFlowEstimatorService.pb.cc \
grpcIOpticalFlowEstimatorService.grpc.pb.cc \
xpcfGrpcModuleMain.cpp
